version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Build Jar/Docker"
      - run: sleep 25
  sit:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to SIT (Int Dev)"
      - run: sleep 15
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Test SIT (Int Dev)"
      - run: sleep 15
  demo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to DEMO"
      - run: sleep 15
  nft:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to NFT"
      - run: sleep 15
  staging:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to STAGING"
      - run: sleep 15        
  prod:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to PRODUCTION"
      - run: sleep 15         

workflows:
  version: 2
  pipeline:
    jobs:
      - build      
      - sit:
          requires:
            - build 
      - test:
          requires:
            - sit           
      - hold:
          type: approval
          requires:
            - test   
      - demo
      - nft
      - staging
      - prod
