version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Build Jar/Docker"
      - run: sleep 25
  sit:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to SIT (Int Dev)"
      - run: sleep 15
  demo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to DEMO"
      - run: sleep 15
  nft:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to NFT"
      - run: sleep 15
  staging:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to STAGING"
      - run: sleep 15        
  prod:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy to PRODUCTION"
      - run: sleep 15        
workflows:
  version: 2
  pipeline:
    jobs:
      - build      
      - sit
          requires:
            - build
      - request-approval-demo:
          type: approval
          requires:
            - sit      
      - demo
          requires:
            - request-approval-demo
      - request-approval-nft:
          type: approval
          requires:
            - demo      
      - nft
          requires:
            - request-approval-nft
      - request-approval-staging:
          type: approval
          requires:
            - nft               
      - staging
          requires:
            - request-approval-staging
      - request-approval-production:
          type: approval
          requires:
            - staging             
      - prod
          requires:
            - request-approval-production          
